### PR TITLE
.NET 6 release!

### PR DESCRIPTION
**Pull request by acesnik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Some gitter discussion about the `lief` errors: https://gitter.im/conda-forge/conda-forge.github.io?at=618ad1cc29ddcd02937263e0

*Might* be unrelated to the eventual segfault though :/

**Comment by acesnik** [comment]
Do you think it could be timing out and killed for some reason? ... It's a pretty strange error. 

I did confirm that the package works on my local machine running macOS.

**Comment by dhirschfeld** [comment]
It's only taking 14mins so I doubt it's a CI timeout.

**Comment by dhirschfeld** [comment]
As a non-mac user I'd be inclined to skip osx for now and open an issue to re-enable the build for anyone whos wants to pick that up... ofc doesn't help if *you* need osx :/

**Comment by dhirschfeld** [comment]
Hi @acesnik :wave:
I tried disabling the binary relocation on OSX. I'm not sure if that's the right thing to do, but it seemed to work `¯\_(ツ)_/¯`

I don't have a Mac to check but the CI seemed to print out the version ok, so if you're happy that it's working, feel free to merge.

**Review by dhirschfeld — APPROVED** [review]

**Comment by acesnik** [comment]
Oh, fantastic! Yeah, that looks great to me! Let's give it a shot.

**Pull request merged**
