### PR TITLE
Package .NET Core 2.1

### PR DESCRIPTION
**Pull request by acesnik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Any particular reason we want to support this? I'd rather tell people to update to a modern .NET than add maintenance burden for a version that will be out of support in a few months.

image

That said, if you want to take this on because you have a desperate need for it then it's fine I guess.

**Comment by acesnik** [comment]
My motivation here is that an important closed-source tool in my field currently requires .NET Core 2.1 (http://coxdocs.org/doku.php?id=maxquant:common:download_and_installation). I'd suggest we just package this once, so that it's available to them but not do continued maintenance.

**Comment by acesnik** [comment]
I'm not attached to the idea or desperate for the version, though, so either way is fine by me.

**Comment by dhirschfeld** [comment]
Since you've already done the work we may as well merge it!

I might get you to retarget the PR (or open a new one) against the `v2` branch though:
https://github.com/conda-forge/dotnet-feedstock/tree/v2

**Comment by acesnik** [comment]
Sounds good! I retargeted `v2`. It should be ready to go.

**Pull request merged**
