### PR TITLE
Test that dotnet-runtime can return runtimes available (v5)

### PR DESCRIPTION
**Pull request by acesnik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by acesnik** [comment]
List of changes:
* Changed `build_platform` to `target_platform` because it seems more precise. Mentioned here (https://github.com/conda-forge/staged-recipes/pull/14623#discussion_r616499322).
* Specify DOTNET_ROOT in the small executable for macOS/Linux. Right now, it's doesn't appear to be set. Not sure how to fix that.
* Test `dotnet --list-runtimes` with `dotnet-runtime`, which is closer to its function

**Comment by acesnik** [comment]
I got the macOS version to run by getting the environment variable activation scripts to the right place.

**Comment by dhirschfeld** [comment]
Thanks for looking into that - it looks like I really did need the tests 😬

**Review by dhirschfeld — APPROVED** [review]

**Comment by dhirschfeld** [comment]
> I got the macOS version to run by getting the environment variable activation scripts to the right place.

This PR looks good to merge (approved)! Do the other PRs need similar changes?

**Comment by acesnik** [comment]
All three are set to review, now. I'll wait to merge until you give the go-ahead for all of them. 👍🏼

**Comment by dhirschfeld** [comment]
> All three are set to review, now. I'll wait to merge until you give the go-ahead for all of them

LGTM. I've approved them all but will leave you to merge :+1:

**Pull request merged**
