### PR TITLE
update v5

### PR DESCRIPTION
**Pull request by acesnik**
Also, alphabetized the targets in meta.yaml

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by acesnik** [comment]
No idea how to fix these ICU build issues. I posted an issue to that feedstock.

**Comment by dhirschfeld** [comment]
> No idea how to fix these ICU build issues.

No idea either, sorry. It seems that ICU installed by CF is being picked up on all platforms other than `aarch64`.
I wonder if the message:
```
Couldn't find a valid ICU package installed on the system
```
...means it couldn't find the CF version *at all*, or that there was some (swallowed) exception when trying to load it.

**Comment by dhirschfeld** [comment]
There's not a huge demand for `aarch64` so maybe we just disable that platform and if someone cares they can try to open a PR to re-enable it?

image

**Comment by acesnik** [comment]
Shoot, it finally happened: I pushed to the wrong remote just now. I'll update the build number...

I already deleted the rogue branches.

image

**Review by dhirschfeld — APPROVED** [review]
:shipit:

**Pull request merged**
