### PR TITLE
Enable OSX build and update to 5.0.201

### LINKED ISSUE #11: Set `DOTNET_MULTILEVEL_LOOKUP=0`?
> When `DOTNET_MULTILEVEL_LOOKUP` is set to 0, .NET ignores any globally installed .NET version. Remove that environment setting to let .NET consider the default global install location when selecting the best framework for running the application. The default is typically C:\Program Files\dotnet, which is where the installers install .NET.

https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#download-and-manually-install

### LINKED ISSUE #14: Revert variable naming
With build 4 it's clearly not working :/
```
The following NEW packages will be INSTALLED:

    dotnet:            5.0.100-h57928b3_4     conda-forge
    dotnet-aspnetcore: 5.0.0-h2d74725_4       conda-forge
    dotnet-desktop:    5.0.0-h57928b3_4       conda-forge
    dotnet-runtime:    5.0.0-h2d74725_4       conda-forge
    dotnet-sdk:        5.0.100-h2d74725_4     conda-forge

```
```
Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.100

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by acesnik**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

----

Resolves #14 
Resolves #11

### CODE REVIEW

**Comment by acesnik** [comment]
@conda-forge-admin, please restart ci

**Comment by acesnik** [comment]
This might be a larger issue with conda-forge/core https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/149

**Comment by acesnik** [comment]
@dhirschfeld @ZimmerA 

This one should be ready for a look. 

The PR aims to enable an OSX build and update .NET to 5.0.201.

We should also consider building 3.1.407 both to release .NET Core 3.1 for osx, since it still an important release, and to get the updated release for linux and windows.

Thanks! -AC

**Comment by dhirschfeld** [comment]
Good work @acesnik - thanks for taking this on! There were a couple of other changes I wanted to make before releasing a new version so I'll try and push those before merging.

**Pull request merged**
